# Generated by Django 4.0.5 on 2022-06-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vehiculo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=80, verbose_name='Nombre Comida'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
