# Generated by Django 4.0.5 on 2022-06-20 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_vehiculo_marca_alter_vehiculo_modelo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='rut',
        ),
    ]
