# Generated by Django 4.0.5 on 2022-06-29 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ventas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='Productos',
        ),
    ]
