# Generated by Django 4.1.3 on 2022-11-06 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_vehiculo_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos2',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80, verbose_name='Nombre Comida')),
                ('modelo', models.CharField(blank=True, max_length=80, null=True, verbose_name='Tipo de servicio')),
                ('imagen', models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=35, verbose_name='Precio')),
                ('estado', models.CharField(blank=True, max_length=80, null=True, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
    ]
