# Generated by Django 4.1.3 on 2022-11-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_productos2'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Estado'),
        ),
    ]
