# Generated by Django 4.1.3 on 2022-11-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_productos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='estado',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
