# Generated by Django 4.1.3 on 2022-11-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ventas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.CharField(max_length=80, verbose_name='Servicio'),
        ),
    ]
